// Label Position scenarios
// Tests how annotation systems handle different label placement patterns

import type { Scenario } from '@/types/scenario';

export const scenarios: Record<string, Scenario> = {
  'd4a1': {
    id: 'd4a1',
    title: 'Personal Settings',
    description: 'User profile settings card with 3 fields (Name, Email, Timezone). Labels positioned to the left with colon, inputs aligned right. Wide spacing between fields.',
    expectedAction: 'FILL',
    expectedTarget: 'email-input',
    labels: [
      'label_position=left',
      'element_density=sparse',
      'action_complexity=single-action',
    ],
  },
  'd5a2': {
    id: 'd5a2',
    title: 'Server Config',
    description: 'Admin configuration panel with 25 settings in two-column grid. Labels on left, inputs on right, compact vertical spacing.',
    expectedAction: 'FILL',
    expectedTarget: 'db-host-input',
    labels: [
      'label_position=left',
      'element_density=moderate',
      'action_complexity=single-action',
    ],
  },
  'd6a3': {
    id: 'd6a3',
    title: 'Trading Order Form',
    description: 'Trading platform order entry with 65 fields in dense 3-column layout. Minimal spacing, grouped sections, multiple tables.',
    expectedAction: 'FILL',
    expectedTarget: 'limit-price-input',
    labels: [
      'label_position=left',
      'element_density=dense',
      'action_complexity=single-action',
    ],
  },
  'd7a4': {
    id: 'd7a4',
    title: 'Calendar Picker',
    description: 'Month calendar with 35 day cells in 5×7 grid. Week labels on left (Week 1, Week 2, etc.), day cells extremely compact with 1px spacing. Localized in 300×250px area.',
    expectedAction: 'CLICK',
    expectedTarget: 'day-22',
    labels: [
      'label_position=left',
      'element_density=extreme-dense',
      'action_complexity=single-action',
    ],
  },
  'e8b2': {
    id: 'e8b2',
    title: 'Newsletter Signup',
    description: 'Newsletter signup modal with Name and Email fields. Labels above inputs, centered layout, generous spacing.',
    expectedAction: 'FILL',
    expectedTarget: 'email-input',
    labels: [
      'label_position=top',
      'element_density=sparse',
      'action_complexity=single-action',
    ],
  },
  'e9b3': {
    id: 'e9b3',
    title: 'Expense Report',
    description: 'Business expense report form with 23 fields across 4 sections (Employee Info, Trip Details, Expenses, Reimbursement). Labels above each input in two-column grid.',
    expectedAction: 'FILL',
    expectedTarget: 'email-input',
    labels: [
      'label_position=top',
      'element_density=moderate',
      'action_complexity=single-action',
    ],
  },
  'eab4': {
    id: 'eab4',
    title: 'Job Application',
    description: 'Employment application form with 28 fields (Contact info, Education, Experience). Standard vertical form with moderate spacing.',
    expectedAction: 'FILL',
    expectedTarget: 'phone-input',
    labels: [
      'label_position=top',
      'element_density=dense',
      'action_complexity=single-action',
    ],
  },
  'ecb5': {
    id: 'ecb5',
    title: 'Appointment Booking',
    description: 'Doctor appointment booking grid with 40 time slots (5 days × 8 hours). Labels on top (Time:, Day headers). Compact grid layout with 1px spacing in 600×400px area.',
    expectedAction: 'CLICK',
    expectedTarget: 'slot-wed-14',
    labels: [
      'label_position=top',
      'element_density=extreme-dense',
      'action_complexity=single-action',
    ],
  },
  'f3c5': {
    id: 'f3c5',
    title: 'Login Form',
    description: 'Modern login page with Email and Password fields. Floating labels animate on focus, large inputs with borders.',
    expectedAction: 'FILL',
    expectedTarget: 'email-input',
    labels: [
      'label_position=inside',
      'element_density=sparse',
      'action_complexity=single-action',
    ],
  },
  'f4c6': {
    id: 'f4c6',
    title: 'Checkout',
    description: 'E-commerce checkout with billing and payment (8 fields). Material design cards, labels float on focus.',
    expectedAction: 'FILL',
    expectedTarget: 'zip-input',
    labels: [
      'label_position=inside',
      'element_density=moderate',
      'action_complexity=single-action',
    ],
  },
  'f5c7': {
    id: 'f5c7',
    title: 'Patient Registration',
    description: 'Patient registration with demographics, insurance, medical history (20 fields). Multi-section material design, very compact.',
    expectedAction: 'FILL',
    expectedTarget: 'policy-number-input',
    labels: [
      'label_position=inside',
      'element_density=dense',
      'action_complexity=single-action',
    ],
  },
  'f6c8': {
    id: 'f6c8',
    title: 'Color Picker',
    description: 'Design tool color palette with 64 color swatches in 8×8 grid. Floating label shows color hex on hover. Compact 400×400px area with 1px spacing.',
    expectedAction: 'CLICK',
    expectedTarget: 'color-ff7f50',
    labels: [
      'label_position=inside',
      'element_density=extreme-dense',
      'action_complexity=single-action',
    ],
  },
  'a7d4': {
    id: 'a7d4',
    title: 'Contact Us',
    description: 'Minimal contact form with Name, Email, Message. Placeholder-only labels, clean design, good spacing.',
    expectedAction: 'FILL',
    expectedTarget: 'name-input',
    labels: [
      'label_position=placeholder',
      'element_density=sparse',
      'action_complexity=single-action',
    ],
  },
  'a8d5': {
    id: 'a8d5',
    title: 'Create Account',
    description: 'User registration with username, email, password, confirm, phone, address (8 fields). Vertical stack, placeholder text only.',
    expectedAction: 'FILL',
    expectedTarget: 'username-input',
    labels: [
      'label_position=placeholder',
      'element_density=moderate',
      'action_complexity=single-action',
    ],
  },
  'a9d6': {
    id: 'a9d6',
    title: 'Customer Feedback Survey',
    description: 'Survey form with 20 questions in two-column grid. Placeholder text only, no labels.',
    expectedAction: 'FILL',
    expectedTarget: 'q15-input',
    labels: [
      'label_position=placeholder',
      'element_density=dense',
      'action_complexity=single-action',
    ],
  },
  'aad7': {
    id: 'aad7',
    title: 'Emoji Reactions',
    description: 'Emoji picker with 64 emojis in 8×8 grid. Tooltip shows emoji code on hover. Compact 450×450px area with 2px spacing.',
    expectedAction: 'CLICK',
    expectedTarget: 'emoji-thumbsup',
    labels: [
      'label_position=placeholder',
      'element_density=extreme-dense',
      'action_complexity=single-action',
    ],
  },
  'b9e6': {
    id: 'b9e6',
    title: 'Product Search',
    description: 'Product search filters with 3 dropdowns. Labels inline to the left of inputs (Category:, Price Range:, Brand:).',
    expectedAction: 'SELECT',
    expectedTarget: 'category-select',
    labels: [
      'label_position=inline',
      'element_density=sparse',
      'action_complexity=single-action',
    ],
  },
  'bae7': {
    id: 'bae7',
    title: 'User Management',
    description: 'Admin data table filters with 10 controls (7 selects, 3 inputs). Labels inline to left of each control. Compact toolbar layout.',
    expectedAction: 'SELECT',
    expectedTarget: 'role-filter',
    labels: [
      'label_position=inline',
      'element_density=moderate',
      'action_complexity=single-action',
    ],
  },
  'bbe8': {
    id: 'bbe8',
    title: 'Invoice Line Items',
    description: 'Invoice entry table with 20 rows × 5 columns = 100 inputs. Each cell has inline label (Item:, Qty:, $:, Tax:, Total:). Very dense table layout.',
    expectedAction: 'FILL',
    expectedTarget: 'qty-12-input',
    labels: [
      'label_position=inline',
      'element_density=dense',
      'action_complexity=single-action',
    ],
  },
  'bce9': {
    id: 'bce9',
    title: 'Theater Seat Selection',
    description: 'Movie theater seat picker with 48 seats in 6×8 grid. Row labels inline to left (A:, B:, C:, etc.). Compact layout with 1px spacing, some seats occupied.',
    expectedAction: 'CLICK',
    expectedTarget: 'seat-c5',
    labels: [
      'label_position=inline',
      'element_density=extreme-dense',
      'action_complexity=single-action',
    ],
  },
  'c2f8': {
    id: 'c2f8',
    title: 'Search Box',
    description: 'Google-style search interface with single search input. No text labels, only icon indicator (magnifying glass emoji).',
    expectedAction: 'FILL',
    expectedTarget: 'search-input',
    labels: [
      'label_position=none',
      'element_density=sparse',
      'action_complexity=single-action',
    ],
  },
  'c3f9': {
    id: 'c3f9',
    title: 'Security Concept Selector',
    description: 'CAPTCHA-style verification grid with 12 text phrase cards. Instruction: "Select the item that represents a security feature." User must understand semantic meaning to identify correct phrase ("Password authentication") vs other categories (Entertainment: "Movie streaming", Communication: "Email inbox", Productivity: "Calendar events", Shopping: "Shopping cart", etc.).',
    expectedAction: 'CLICK',
    expectedTarget: 'item-password-auth',
    labels: [
      'label_position=none',
      'element_density=moderate',
      'action_complexity=single-action',
      'instruction=semantic-reasoning-required',
    ],
  },
  'c4fa': {
    id: 'c4fa',
    title: 'Monthly Appointment Scheduler',
    description: 'Calendar with 31 days × 3 time slots = 93 inputs. Grid layout with emoji column headers (🌅, 🌞, 🌙). No text labels, only emoji indicators.',
    expectedAction: 'FILL',
    expectedTarget: 'day-15-afternoon',
    labels: [
      'label_position=none',
      'element_density=dense',
      'action_complexity=single-action',
    ],
  },
  'c5fb': {
    id: 'c5fb',
    title: 'Virtual Keyboard',
    description: 'On-screen keyboard with 40 keys in 5-row layout. No labels, keys show only their character. Includes numbers, QWERTY letters, and special keys.',
    expectedAction: 'CLICK',
    expectedTarget: 'key-m',
    labels: [
      'label_position=none',
      'element_density=extreme-dense',
      'action_complexity=single-action',
    ],
  },
} as const;
