name: Highlighter Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:  # Allows manual triggering from GitHub Actions UI

jobs:
  highlighter-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout probo-qa
        uses: actions/checkout@v4

      - name: Setup CI environment
        run: cp .env.ci .env

      - name: Verify .env file
        run: |
          if [ -f .env ]; then
            echo "✓ .env file exists"
            cat .env
          else
            echo "✗ .env file not found"
            exit 1
          fi

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies (includes @probolabs/highlighter from npm)
        run: pnpm install --frozen-lockfile

      - name: Verify highlighter bundle exists
        run: |
          if (Test-Path "node_modules/@probolabs/highlighter/dist/probolabs.umd.js") {
            Write-Host "✓ Highlighter bundle found in node_modules"
            Get-Item "node_modules/@probolabs/highlighter/dist/probolabs.umd.js" | Select-Object Name, Length
          } else {
            Write-Error "✗ Highlighter bundle not found"
            exit 1
          }
        shell: pwsh

      - name: Install Playwright browsers
        run: pnpm exec playwright install --with-deps chromium

      - name: Setup database
        run: pnpm exec prisma generate && pnpm exec prisma db push

      - name: Clear Next.js cache
        run: rm -rf .next

      - name: Verify environment before tests
        run: |
          echo "Contents of .env:"
          cat .env
          echo ""
          echo "Highlighter bundle exists:"
          ls -lh node_modules/@probolabs/highlighter/dist/probolabs.umd.js

      - name: Test env vars are passed to Next.js
        run: |
          echo "Starting Next.js dev server to test env vars..."
          HIGHLIGHTER_SCRIPT_PATH=node_modules/@probolabs/highlighter/dist/probolabs.umd.js DATABASE_URL=file:./test.db SCENARIO_CACHE_DIR=.cache/scenarios PORT=3099 pnpm dev &
          SERVER_PID=$!
          echo "Server PID: $SERVER_PID"

          # Wait for server to start
          echo "Waiting for server to start..."
          sleep 10

          # Test the API endpoint
          echo "Testing /api/scenarios/check-highlighter endpoint..."
          curl -v http://localhost:3099/api/scenarios/check-highlighter || true

          # Kill the server
          echo "Stopping server..."
          kill $SERVER_PID || true
          sleep 2
        env:
          CI: true

      - name: Run highlighter tests
        run: pnpm test tests/specs/highlighter.spec.ts
        env:
          CI: true

      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: highlighter-test-artifacts
          path: |
            playwright-report/
            test-results/
            .cache/scenarios/
          retention-days: 7
