name: Highlighter Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  highlighter-tests:
    runs-on: windows-latest
    timeout-minutes: 15

    steps:
      - name: Checkout probo-qa
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies (includes @probolabs/highlighter from npm)
        run: pnpm install --frozen-lockfile

      - name: Verify highlighter bundle exists
        run: |
          if (Test-Path "node_modules/@probolabs/highlighter/dist/probolabs.umd.js") {
            Write-Host "✓ Highlighter bundle found in node_modules"
            Get-Item "node_modules/@probolabs/highlighter/dist/probolabs.umd.js" | Select-Object Name, Length
          } else {
            Write-Error "✗ Highlighter bundle not found"
            exit 1
          }
        shell: pwsh

      - name: Install Playwright browsers
        run: pnpm exec playwright install --with-deps chromium

      - name: Setup database
        run: pnpm exec prisma generate && pnpm exec prisma db push
        env:
          DATABASE_URL: file:./test.db

      - name: Run highlighter tests
        run: pnpm test tests/specs/highlighter.spec.ts
        env:
          DATABASE_URL: file:./test.db
          HIGHLIGHTER_SCRIPT_PATH: node_modules/@probolabs/highlighter/dist/probolabs.umd.js
          SCENARIO_CACHE_DIR: .cache/scenarios
          CI: true
          PORT: 3000

      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: highlighter-test-artifacts
          path: |
            playwright-report/
            test-results/
            .cache/scenarios/
          retention-days: 7
